name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build Spring Boot JAR
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/spring-boot-sample
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "Building with $JAR_FILE"
          docker build --build-arg JAR_FILE=$JAR_FILE -t $IMAGE_NAME:latest .

      # Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/spring-boot-sample
          docker push $IMAGE_NAME:latest
